spring.application.name=ninjas

#URL de conexão com o banco PostgreSQL (endereço + porta + nome do banco)
spring.datasource.url=jdbc:postgresql://localhost:5432/ninjas

#Usuario do banco de dados
spring.datasource.username=postgres

#A senha do banco de dados 
spring.datasource.password=postdba

#Driver é responsavel por fazer a conexao com o postgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

#Define como o hibernate vai gerenciar as tabelas(update = cria/atualiza sem apagar dados)
spring.jpa.hibernate.ddl-auto=update

#Mostra no console as consultas SQL executadas 
spring.jpa.show-sql=true

#Formata o SQL exibido no console para facilitar a leitura 
spring.jpa.properties.hibernate.format_sql=true

#Define o tipo de banco utilizado (dialeto do PostgreSQL)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
