spring.application.name=ninja
#url de conexão com o banco PostgreSQL (endereço + porta + nome do banco)
spring.datasource.url=jdbc:postgresql://localhost:5432/ninjas
#usuario do banco de daods
spring.datasource.username=postgres
#senha do banco de dados
spring.datasource.password=postdba
#driver responsavel por fazer a conexao com o POSTGREsql
spring.datasource.driver-class-name=org.postgresql.Driver
#define como o hibernate vai gerenciar as tabelas (update = cria/atualiza sem apagar dados)
spring.jpa.hibernate.ddl-auto=update
#mostra no console as consultas SQL executadas
spring.jpa.show-sql=true
#formata o SQL exibido no console para facilitar leitura
spring.jpa.properties.hibernate.format_sql=true
#define o tipo de banco utilizado (dialeto do PostgreSQL)
spring.jpa.database-plataform=org.hibernate.dialect.postgreSQLDialect
